### ISSUE TITLE
Add Exception Handling To Bookmarks Windows

### ISSUE THREAD

**Issue by MattMoradi** [hudson1740/Brett-Tech-Browser#2]
If the user clicks on the option to "LOAD" a bookmark but does not have a bookmark selected, the .NET Runtime throws an unhandled AmbiguousMatchException. I advise wrapping this code block in a try-catch sequence in order to handle the AmbiguousMatchException.

![ambiguousmatchexception](https://user-images.githubusercontent.com/14935352/28051070-9d632368-65b6-11e7-8bbc-f205309fe553.PNG)

**Comment by hudson1740** [comment]
fixed
